### ISSUE TITLE
Need a standard Schema for SMIS161

### ISSUE THREAD

**Issue by dugganj** [OpenPegasus/OpenPegasus#43]
The interface from SCVMM to CIM requires SMI-S 1.6.1.  There is no standard Schema for SMIS161 in the Pegasus 14.2 distribution.

According to the SNIA web page at https://www.snia.org/tech_activities/standards/curr_standards/smi, SMI-S 1.6.1 requires:
  - The CIM 2.41 schema.  We have determined that 1.6.1 requires the *experimental* schema
  - The SMI-S mofs available at https://www.snia.org/sites/default/files/SNIAMOFs-1-6-1-Rev5.zip

We have tried to build this schema by hand, using various methods.  One issue we keep running into is that the class CIM_LogicalDevice (defined in Core/CIM_LogicalDevice.mof) inherits from CIM_AllocatedLogicalElement class in the experimental schema.  I have tried to get this to resolve correctly, to no avail.

We finally resorted to editing the file Core/CIM_LogicalDevice.mof to have the class inherit from CIM_EnabledLogicalElement.  Once we do this, it is possible to put together a schema that loads.

**Comment by KSchopmeyer** [comment]
The correct schema is really DMTF CIMExperimental241. Pegasus has now implemented this  experimental schema into the schemas available within the OpenPegasus 2.4.1 Experimental (Directory (pegasus/Schemas/CIMExperimental241) github 14.2 release.  Note that this was done by manually creating the correct ordering of the files in CIM_Core.mof, etc. so the process of actually compiling a new schema is not yet automated as it is in pywbem and pywbemtools.

The actual problem was fixed with pr #51 which incorporated both the fix to OpenPegasus itself and the correct set of files to compile DMTF Schema 2.4.1 Experimental.
